version: "3"

services:

    cam:
        image: alejandrocolomar/rob_cam:cam
        devices:
            - "/dev/video0:/dev/video0"
        environment:
            - ROBOT_TYPE=ur
#            - ROBOT_TYPE=kwr
            - ROBOT_ADDR=192.168.0.1
            - ROBOT_PORT=30002
#            - ROBOT_PORT=23
            - ROBOT_USER=as
            - ROBOT_PASSWD=
            - ROBOT_STATUS_FNAME=status.log
            - ROB_PORT=13100
            - ROB_CAMS_MAX=1
            - DELAY_LOGIN=1000000
            - DELAY_US=100000

    rob:
        image: alejandrocolomar/rob_cam:rob
        environment:
            - ROB_ADDR=rob
            - ROB_PORT=13100
            - CAMERA_IDX=0
            - DELAY_US=10000

    robot:
        image: alejandrocolomar/rob_cam:ur-sim
#        image: secobau/telnetd:alpine
