###############################################################################
#        Copyright (C) 2020        Alejandro Colomar Andrés                   #
#        SPDX-License-Identifier:  GPL-2.0-only                               #
###############################################################################
---
apiVersion: apps/v1
kind: secret
metadata:
    name: cam-secret
type: Opaque
stringData:
    CAMERA_IDX: "0"
    DELAY_US: "10000"
    ROB_ADDR: "rob"
    ROB_PORT: "13100"
---
################################################################################
#kubectl apply  --filename cam-secret.yaml                                     ;
#kubectl delete --filename cam-secret.yaml                                     ;
################################################################################
