###############################################################################
#        Copyright (C) 2020        Sebastian Francisco Colomar Bauza          #
#        SPDX-License-Identifier:  GPL-2.0-only                               #
###############################################################################
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: robot
spec:
    selector:
        matchLabels:
            name: robot
    template:
        metadata:
            labels:
                name: robot
        spec:
            containers:
                -   name: robot
                    image: alejandrocolomar/rob_cam:ur-sim_0.5
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: rob
spec:
    selector:
        matchLabels:
            name: rob
    template:
        metadata:
            labels:
                name: rob
        spec:
            initContainers:
            -   name: init
                image: busybox
                command:
                -   sh
                -   -c
                -   sleep 1
            containers:
            -   name: rob
                image: alejandrocolomar/rob_cam:rob_0.5
                env:
                -   name: DELAY_LOGIN
                    valueFrom:
                        secretKeyRef:
                            name: rob-secret
                            key: DELAY_LOGIN
                -   name: DELAY_US
                    valueFrom:
                        secretKeyRef:
                            name: rob-secret
                            key: DELAY_US
                -   name: ROB_CAMS_MAX
                    valueFrom:
                        secretKeyRef:
                            name: rob-secret
                            key: ROB_CAMS_MAX
                -   name: ROB_PORT
                    valueFrom:
                        secretKeyRef:
                            name: rob-secret
                            key: ROB_PORT
                -   name: ROBOT_ADDR
                    valueFrom:
                        secretKeyRef:
                            name: rob-secret
                            key: ROBOT_ADDR
                -   name: ROBOT_PASSWD
                    valueFrom:
                        secretKeyRef:
                            name: rob-secret
                            key: ROBOT_PASSWD
                -   name: ROBOT_PORT
                    valueFrom:
                        secretKeyRef:
                            name: rob-secret
                            key: ROBOT_PORT
                -   name: ROBOT_STATUS_FNAME
                    valueFrom:
                        secretKeyRef:
                            name: rob-secret
                            key: ROBOT_STATUS_FNAME
                -   name: ROBOT_TYPE
                    valueFrom:
                        secretKeyRef:
                            name: rob-secret
                            key: ROBOT_TYPE
                -   name: ROBOT_USER
                    valueFrom:
                        secretKeyRef:
                            name: rob-secret
                            key: ROBOT_USER
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: cam
spec:
    selector:
        matchLabels:
            name: cam
    template:
        metadata:
            labels:
                name: cam
        spec:
            initContainers:
            -   name: init
                image: busybox
                command:
                -   sh
                -   -c
                -   sleep 2
            containers:
            -   name: cam
                image: alejandrocolomar/rob_cam:cam_0.5
                volumeMounts:
                -   name: dev-video0
                    mountPath: /dev/video0
                securityContext:
                    privileged: true
                env:
                -   name: CAMERA_IDX
                    valueFrom:
                        secretKeyRef:
                            name: cam-secret
                            key: CAMERA_IDX
                -   name: DELAY_US
                    valueFrom:
                        secretKeyRef:
                            name: cam-secret
                            key: DELAY_US
                -   name: ROB_ADDR
                    valueFrom:
                        secretKeyRef:
                            name: cam-secret
                            key: ROB_ADDR
                -   name: ROB_PORT
                    valueFrom:
                        secretKeyRef:
                            name: cam-secret
                            key: ROB_PORT
            volumes:
            -   name: dev-video0
                hostPath:
                    path: /dev/video0
---
apiVersion: v1
kind: Service
metadata:
    name: robot
spec:
    selector:
        name: robot
    ports:
    -   port: 30002
---
apiVersion: v1
kind: Service
metadata:
    name: rob
spec:
    selector:
        name: rob
    ports:
    -   port: 13100

################################################################################
#sudo apt-get update && sudo apt-get install -y apt-transport-https curl       ;
#echo deb http://apt.kubernetes.io/ kubernetes-xenial main                     \
#        | sudo tee -a /etc/apt/sources.list.d/kubernetes.list                 ;
#curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg                 \
#        | sudo apt-key add -                                                  ;
#sudo apt-get update && sudo apt-get install -y docker-ce                      ;
#sudo apt-get install -y kubelet kubeadm kubectl                               ;
#sudo apt-mark hold kubelet kubeadm kubectl                                    ;
#ip=< PRIVATE IP OF THE KUBERNETES MASTER >                                    ;
#echo $ip k8smaster | sudo tee -a /etc/hosts                                   ;
#sudo kubeadm init                                                             \
#        --control-plane-endpoint=k8smaster                                    \
#        --pod-network-cidr=192.168.0.0/16                                     \
#        --ignore-preflight-errors=all                                         ;
#mkdir -p $HOME/.kube                                                          ;
#sudo cp /etc/kubernetes/admin.conf $HOME/.kube/config                         ;
#sudo chown $(id -u):$(id -g) $HOME/.kube/config                               ;
#kubectl apply -f https://docs.projectcalico.org/v3.8/manifests/calico.yaml    ;
#echo "source <(kubectl completion bash)" >> ~/.bashrc                         ;
#kubectl taint node ideapad node-role.kubernetes.io/master:NoSchedule-         ;
#kubectl apply  --filename kube-compose.yaml                                   ;
#kubectl delete --filename kube-compose.yaml                                   ;
################################################################################
