###############################################################################
#        Copyright (C) 2020        Alejandro Colomar Andrés                   #
#        Copyright (C) 2020        Sebastian Francisco Colomar Bauza          #
#        SPDX-License-Identifier:  GPL-2.0-only                               #
###############################################################################
---
apiVersion: v1
kind: Secret
metadata:
    name: cam-secret
stringData:
    CAMERA_IDX: "0"
    DELAY_US: "10000"
    ROB_ADDR: "rob"
    ROB_PORT: "13100"
type: Opaque
---
apiVersion: v1
kind: Secret
metadata:
    name: rob-secret
stringData:
    DELAY_LOGIN: "1000000"
    DELAY_US: "100000"
    ROB_CAMS_MAX: "1"
    ROB_PORT: "13100"
    ROBOT_ADDR: "robot"
    ROBOT_PASSWD: ""
    ROBOT_PORT: "30002"
    ROBOT_STATUS_FNAME: "status.log"
#    ROBOT_TYPE: "kwr"
    ROBOT_TYPE: "ur"
    ROBOT_USER: ""
type: Opaque
---
################################################################################
#kubectl apply  --filename kube-secrets.yaml                                   ;
#kubectl delete --filename kube-secrets.yaml                                   ;
################################################################################
